### ISSUE TITLE
return non-zero for missing input values

### ISSUE THREAD

**Issue by shantanugadgil** [wrouesnel/p2cli#15]
can p2cli be made to return non-zero if there are missing input values?

right now it seems to return 0 even if input values are missing.

```bash
❯ p2 --template example.tpl --input example.vars.json --format json
Hello, my name is
❯  echo $?
0
❯ cat example.tpl
Hello, my name is {{ name }}
❯ cat example.vars.json
{
    "foo": "bar"
}
```

**Comment by wrouesnel** [comment]
This isn't really possible while still supporting environment variables where that's important. If json structure is important, really you need to validate your own schema before feeding to the template.

In a practical sense: p2 doesn't give me any options to detect this AFAIK, so otherwise a flag would be possible.

**Comment by shantanugadgil** [comment]
I was hoping `p2` has something equivalent of `jinja2`'s equivalent of "error if variable is unset"
